services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ultragedy
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d  
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    restart: always
  server:
    build:
      context: ./backend/app
    container_name: server
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

volumes:
  pgdata:
